services:
  db:
    hostname: db
    image: ankane/pgvector
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env.docker
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: docu-mentor-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - db
    env_file:
      - .env.docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
